version: '3'

services:
    pg:
        image: postgres:14-alpine
        container_name: database
        environment:
            - POSTGRES_DB=library
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
